config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :articulos

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
    has_many :comentarios
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
    belongs_to :articulo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo creado.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'El articulo fue eliminado sastisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:titulo, :cuerpo, :fecha)
    end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @articulo = Articulo.find_by_id(params[:articulo_id])
    @comentario = Comentario.new(articulo_id: @articulo.id)
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario creado sastisfactoriamente' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario actualizado sastisfactoriamente' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'El comentario fue eliminado sastisfactoriamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:autor, :cuerpo, :fecha, :articulo_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/articulos/_form.html.erb
<%= form_for(@articulo) do |f| %>
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
      <% @articulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field input-group">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>
  <div class="field input-group">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo, class: "form-control" %>
  </div>
  <div class="field input-group">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha%>
  </div>
  <div class="actions">
    <%= f.submit "Enviar", :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1>Editar  Articulo</h1>

<%= render 'form' %>

<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">
    <li class="active"> <%= link_to 'Mostrar', @articulo %> </li>
    <li class="active"> <%= link_to 'Atras', articulos_path %> </li>
  </ul>
</nav>
 

app/views/articulos/index.html.erb
<% unless notice.blank? %>
  <div class="alert alert-info" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<h1>Listado de  Articulos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.titulo %></td>
        <td><%= articulo.cuerpo %></td>
        <td><%= articulo.fecha %></td>
        <td><%= link_to 'Ver', articulo %></td>
        <td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
        <td><%= link_to 'Eliminar', articulo, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Articulo', new_articulo_path %>



<ul class="media-list">
  <li class="media"> <span class="glyphicon glyphicon-search" aria-hidden="true"></span>  A Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 
    <ul >
      <li class="media"> <span class=" glyphicon glyphicon-cutlery" aria-hidden="true"></span> AA Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 
    
      </li>
      <li class="media">BB Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 
        
      </li>
      
      <li class="media">CC Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 
      </li>
    </ul>  
  </li>
  
  <li class="media">B Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 
    
  </li>
  
  <li class="media">C Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 
  </li>
  
</ul>





<div class="container">
  <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 columns as the device or viewport size increases. It includes predefined classes for easy layout options, as well as powerful mixins for generating more semantic layouts.
      </div>
      
      <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 columns as the device or viewport size increases. It includes predefined classes for easy layout options, as well as powerful mixins for generating more semantic layouts.
      </div>
      
      <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 columns as the device or viewport size increases. It includes predefined classes for easy layout options, as well as powerful mixins for generating more semantic layouts.
      </div>
      
      <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      Bootstrap includes a responsive, mobile first fluid grid system that appropriately scales up to 12 columns as the device or viewport size increases. It includes predefined classes for easy layout options, as well as powerful mixins for generating more semantic layouts.
      </div>
    
  </div>
</div>

app/views/articulos/new.html.erb
<h1>Nuevo Articulo</h1>

<%= render 'form' %>

<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">
    <li class="active"> <%= link_to 'Atras', articulos_path %> </li>
  </ul>
</nav>
 

app/views/articulos/show.html.erb
<% unless notice.blank? %>
  <div class="alert alert-info" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<p>
  <strong>Titulo:</strong>
  <%= @articulo.titulo %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @articulo.cuerpo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @articulo.fecha %>
</p>
<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">
    <li class="active"> <%= link_to 'Nuevo Comentario', new_comentario_path(articulo_id: @articulo.id) %></li>
    <li class="active"> <%= link_to 'Editar', edit_articulo_path(@articulo) %> </li>
    <li class="active"> <%= link_to 'Atras', articulos_path %></li>
  </ul>
</nav>


<h2 id="tit">Comentarios</h2>
<!--
<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Cuerpo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulo.comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.autor %></td>
        <td><%= comentario.cuerpo %></td>
        <td><%= comentario.fecha %></td>
        <td><%= link_to 'Ver', comentario %></td>
        <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Eliminar', comentario, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->


<!--prueba Mia -->

<ul class="media-list">
  <% @articulo.comentarios.each do |comentario| %>
    <li class="media-left"><b> Autor:</b>  <%= comentario.autor %>  
    
    <li class="media-left"><b>Cuerpo:</b>  <%= comentario.cuerpo %> 
              
    </li>
            
    <li class="media-left"><b>Fecha: </b><%=comentario.fecha %>
      
    </li>
    
    
    <%= link_to 'Ver', comentario %>  <%= link_to 'Editar', edit_comentario_path(comentario) %> <%= link_to 'Eliminar', comentario, method: :delete, data: { confirm: '¿Estás seguro?' } %>
   <br></br>
    </li> 
  <% end %>
</ul>

<!--Fin de mi prueba -->

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
<%= f.hidden_field :articulo_id %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form' %>
<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">
    <li class="active"> <%= link_to 'Mostrar', @comentario %>  </li>
    <li class="active"> <%= link_to 'Atras', @comentario.articulo %>  </li>
  
  </ul>
</nav>


<!--<%= link_to 'Atras', articulo_path(@comentario.articulo_id) %>-->

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Cuerpo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.autor %></td>
        <td><%= comentario.cuerpo %></td>
        <td><%= comentario.fecha %></td>
        <td><%= link_to 'Ver', comentario %></td>
        <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Eliminar', comentario, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form' %>

<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">
    <li class="active"> <%= link_to 'Atras', @comentario.articulo %> </li>

  </ul>
</nav>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @comentario.autor %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @comentario.cuerpo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @comentario.fecha %>
</p>

<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">
    <li class="active"> <%= link_to 'Editar', edit_comentario_path(@comentario) %> </li>
    <li class="active"> <%= link_to 'Atras', @comentario.articulo %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  
</head>
<body>

<%= yield %>
Hecho por "Jose Rangel" <br> @Asavior2 </center>

</body>
</html>